---
title: "Lab12"
author: "Anna Matarazzo"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r}
?lm
```

```{r}
some_data <- data.frame(Y_dv=c(1,2,4,3,5,4,6,5),
                        X_iv=c(3,5,4,2,6,7,8,9))

lm(Y_dv ~ X_iv, data=some_data)

save_model <- lm(Y_dv ~ X_iv, data=some_data)
summary(save_model)$r.squared

cor.test(some_data$Y_dv, some_data$X_iv)
summary(save_model)$r.squared
sqrt(summary(save_model)$r.squared)

```



NOT FINISHED:
```{r}
some_data <- data.frame(Y_dv=c(1,2,4,3,5,4,6,5),
                        X_iv=c(3,5,4,2,6,7,8,9))

lm(Y_dv ~ X_iv, data=some_data)


```

```{r}
library(ggplot2)

ggplot(some_data, aes(x=X_iv, y=Y_dv))+
  geom_point()+
  geom_smooth(method='lm', se=FALSE)
```

```{r}
some_data2 <- data.frame(Y=rnorm(4*10,0,1),
                         X=rnorm(4*10,0,1),
                         set=rep(1:4, each=10))


ggplot(some_data2, aes(x=X, y=Y))+
  geom_point()+
  geom_smooth(method='lm', se=FALSE)+
  facet_wrap(~set)
```



HERE IS MORE STUFF



```{r}
library(ggpmisc)
formula <- y ~ x
ggplot(some_data, aes(x=X_iv, y=Y_dv))+
  geom_point()+
  stat_smooth(method="lm", formula = formula)+
  stat_poly_eq(formula=formula, parse=TRUE)
```

NOT FINISHED:

```{r}
library(ggplot2)
library(gganimate)
library(dplyr)

d <- mtcars
fit <- lm(mpg ~ hp, data = d)
d$predicted <- predict(fit)
d$residuals <- residuals(fit)

coefs <- coef(lm(mpg ~ hp, data=mtcars))
coefs[1]
coefs[2]



```


```{r}
some_data <- data.frame(Y_dv=c(1,2,4,3,5,4,6,5),
                        X_iv=c(3,5,4,2,6,7,8,9))

ggplot(some_data, aes(x=X, y=Y))+
  geom_point()

predict.lm(lm(Y))



```


```{r}
some_data <- data.frame(Y_dv=c(1,2,4,3,5,4,6,5),
                        X_iv=c(3,5,4,2,6,7,8,9)) %>%
  mutate(Y_pred=predict.lm(lm(Y~X)))

ggplot(some_data, aes(x=X, y=Y))+
  geom_point()+
  geom_smooth(method='lm', se=FALSE)
```


```{r}

```


```{r}

```


```{r}

```




