---
title: "Lab11"
author: "Anna Matarazzo"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
A <- c(1,2,3,4,5,6,7,8,9,10)
B <- c (1,3,2,4,3,5,4,5,6,7)

plot(A, B)
cor(A,B)
```

```{r}
A <- matrix(rnorm(100,0,1), ncol=10, nrow=10)
B <- c(1,3,2,4,3,5,4,5,6,7)
cor(A,B)
```

```{r}
A <- matrix(rnorm(25,0,1), ncol=5, nrow=5)
B <- matrix(rnorm(25,0,1), ncol=5, nrow=5)
cor(A,B)
```

```{r}
A <- c(1,2,3,4,5)
B <- c(5,2,3,1,4)
cor(A,B)

A_z <- (A-mean(A))/sd(A)
B_z <- (B-mean(B))/sd(B)
sum(A_z*B_z)/4     #n-1



sd_pop <- function(x){
  sqrt(sum(x-mean(x))^2/length(x))
}

A_z <- (A-mean(A))/sd_pop(A)
B_z <- (B-mean(B))/sd_pop(B)
c <- sum(A_z*B_z)/5
c
#????
```

```{r}
A <- c(1,2,3,4,5)
B <- c(5,2,3,1,NA)
cor(A,B)

cor(A,B, use="complete.obs")
```

```{r}
A <- c(1,2,3,4,5)
B <- c(5,2,3,1,4)
cor.test(A,B)
```

```{r}
A <- c(1,2,3,4,5)
B <- c(5,2,3,1,4)
results <- cor.test(A,B)

results$statistic  #t-value
results$parameter  #df
results$p.value
results$estimate   #r
```

```{r}
X <- 1:10
Y <- 1:10

plot(X,Y)

c <- cor(X,Y)
c
```

```{r}
X <- 1:10
Y <- 10:1

plot(X,Y)

cor(X,Y)
```

```{r}
X <- 1:10
Y <- sample(10:1)

plot(X,Y)

cor(X,Y)
```

```{r}
X <- 1:10
Y <- 1:10
X*Y
sum(X*Y)
```

```{r}
X <- 1:10
Y <- 10:1
X*Y
sum(X*Y)
```

```{r}
sum(sample(1:10)*sample(1:10))
```

```{r}
sim_sums <- replicate(1000,sum(sample(1:10)*sample(1:10)))
hist(sim_sums)

min(sim_sums)
max(sim_sums)

```

```{r}
X <- rnorm(10,0,1)
Y <- rnorm(10,0,1)
cor(X,Y)
```

```{r}
replicate(10,cor(rnorm(10,0,1),rnorm(10,0,1)))
```

```{r}
rand_1000 <- replicate(1000,cor(rnorm(10,0,1),rnorm(10,0,1)))
hist(rand_1000)
```

```{r}
mean(rand_1000)
max(rand_1000)
min(rand_1000)

length(rand_1000[rand_1000 >.55])/10000
```

```{r}
rand_1000 <- replicate(1000,cor(rnorm(100,0,1),rnorm(100,0,1)))
hist(rand_1000)

mean(rand_1000)
max(rand_1000)
min(rand_1000)

length(rand_1000[rand_1000 >.55])/10000
```

```{r}
library(ggplot2)
library(ggrepel)

Words = c('bag', 'buckle', 'on', 'insane', 'by', 'monastery', 'relief', 'slope','scoubdrel','loss','holiday','pretentious','solid','time','gut','tarantula','generality','arise','blot','infectious')

Length=c(3,6,2,6,2,9,6,5,9,4,7,11,5,4,3,9,10,5,4,10)
Meanings=c(8,4,10,1,11,1,4,3,1,6,2,1,9,3,4,1,3,3,3,2)

all <- data.frame(Words,Length,Meanings)
knitr::kable(all)

```

```{r}
ggplot(all,aes(x=Length, y=Meanings))+
  geom_point()+
  geom_text_repel(aes(label=Words))
```

```{r}

```








```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```












